### PR TITLE
Add Wi-Fi Satellite types

### PR DESCRIPTION
**Pull request by samuelthomas2774**

### CODE REVIEW

**Comment by Supereg** [comment]
Did you test the different `WiFiSatelliteStatus` values. I'm a bit confused as I though I remembered that I got the connected state for a value of `2` and not `1` as your code suggests it while playing around with it the day before yesterday. But could well be that I messed stuff up 😅

**Comment by samuelthomas2774** [comment]
Yes, `1` shows Connected in the list and the "This accessory is not certified..." message in the accessory settings page. `0` and `2` show Not Connected in the list, `0` shows "Unknown" in the accessory settings page and `2` shows "Satellite Not Connected".

**Comment by Supereg** [comment]
Okidoke 👍🏽

**Comment by KhaosT** [comment]
Thank you ^^

**Pull request merged**
