### PR TITLE
Motion Sensor File

### PR DESCRIPTION
**Pull request by legotheboss**
Created a sample motion sensor file, would be a great resource to add to the accessories folder.

### CODE REVIEW

**Comment by KhaosT** [comment]
Would you mind I ask what's the purpose of this...? It's not like this demonstrates how to inform HomeKit about value changes out side the HomeKit and it doesn't provide anything new compares to existing examples.

**Comment by legotheboss** [comment]
Thought it might be a good resource for anyone who wants to create a motion sensor, but did not want to rewrite a lot of code...

**Comment by KhaosT** [comment]
If you say so ^^ Personally I still think people should at least have basic understanding of what they are doing instead of just edit stuff they don't understand.

**Comment by smith288** [comment]
I think these types of examples are great for beginner and people just wanting to template off it.

**Comment by Maxmudjon** [comment]
how to add MQTT ?

**Pull request merged**
