### PR TITLE
EventedHTTPServer: Don’t assume high-numbered ports aren’t in use (#131).

### PR DESCRIPTION
**Pull request by nriley**
This version actually tries a different port if the OS-generated port is in use...

### CODE REVIEW

**Comment by KhaosT** [comment]
Thanks ^^ Would you mind to bring this change also to the [external HAP Server](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/Accessory.js#L468) in the same PR so that user will no longer need to worry about ports at all?

**Comment by snowdd1** [comment]
@KhaosT : Could you explain the use of the "internal" http Server in short? I thought it would be used for communication with the (ios) Clients as well!
Thanks

**Comment by KhaosT** [comment]
@snowdd1 HomeKit IP Accessory is basically just a normal HTTP Server that handles request. The only thing special is that once we finished ``pair-verify``, the protocol enforces a secure session that requires encrypt the underlying tcp socket communication. I wasn't able to find a way to modify the underlying socket before the data reaches node's http server so we ended up with a two layer structure that internally we use node's http module to host the HAP Server (plain text) and externally we use a normal tcp server (with net module) to relay request and encrypt/decrypt data to HAP Server (internal)

**Comment by KhaosT** [comment]
alright, I'll do the external server part :) Thanks for the PR ^^

**Comment by nriley** [comment]
Sorry I've been busy! Appreciate it.

**Pull request merged**
