### PR TITLE
Create multipleLightAccessories_accfactory.js

### PR DESCRIPTION
**Pull request by OczkoSX**
Create multiple lights within one file with very easy and simple config

### CODE REVIEW

**Comment by KhaosT** [comment]
This one will not be merged since I don't want to encourage people use hap-nodejs as a standalone program. Accessories under `/accessories` mainly serve as examples and in this case, having one light and multiple is the same.

**Comment by OczkoSX** [comment]
So maybe show them how to use the accfactory? So they can do it on themselves. I was lucky that i found it in the files. That was the thing i tried to achieve with this example

**Comment by KhaosT** [comment]
No, people should create their own js file to start the accessory instead of relying on Core/BridgedCore.

**Comment by OczkoSX** [comment]
Okay, sure. I got it

**Pull request closed without merging**
