### PR TITLE
Basic TV support

### PR DESCRIPTION
**Pull request by KhaosT**
Add basic TV support based on implementation in iOS 12.2 beta 1.

### CODE REVIEW

**Comment by gchokov** [comment]
@KhaosT thank you for everything that you do!

**Comment by Gruni22** [comment]
@KhaosT - again very good work. Is there any chance to integrate the receiver service also?

**Comment by KhaosT** [comment]
@Gruni22 what is "receiver service"?

**Comment by Gruni22** [comment]
https://www.apple.com/ios/home/accessories/#section-tv
Sorry I meant the Receiver Accesory. Seems to be for AV receivers

**Pull request merged**
