### PR TITLE
Simplify Characteristic properties

### PR DESCRIPTION
**Pull request by nfarina**
- Use new Characteristic "props" to store things like minValue, etc.
 - New chainable method Characteristic.setProps()
 - Fix for 'int' characteristic formats

### CODE REVIEW

**Comment by cflurin** [comment]
@nfarina: I'm not sure whether to use it this way:
```javascript
      this.Characteristic.CurrentHorizontalTiltAngle.setProps.minValue = 0;
      this.Characteristic.CurrentHorizontalTiltAngle.setProps.minStep = 5;
```

**Comment by nfarina** [comment]
Take a look at `HomeKitTypes.js` - you would do something like this:

```js
this.Characteristic.CurrentHorizontalTiltAngle.setProps({ minValue: 0, minStep: 5 });
```

**Comment by cflurin** [comment]
```javascript
    this.Characteristic.CurrentHorizontalTiltAngle.setProps({ minValue: 0, minStep: 5 });
```
It runs but it doesn't change the default values.
Neither I can see the setting in ...51826/accessories

**Comment by nfarina** [comment]
I assume `this.Characteristic` is an instance of the class and not the class itself?

**Comment by nfarina** [comment]
OK nevermind I can reproduce this, investigating...

**Comment by cflurin** [comment]
correct:
```javascript
this.Characteristic.TargetHorizontalTiltAngle = FhemWindowCoveringService
        .addCharacteristic(Characteristic.TargetHorizontalTiltAngle)
        .on('get', this.getTargetHorizontalTiltAngle.bind(this))
        .on('set', this.setTargetHorizontalTiltAngle.bind(this));
      
this.Characteristic.CurrentHorizontalTiltAngle.setProps({ minValue: 0, minStep: 5 })
```

**Comment by nfarina** [comment]
OK just pushed a few fixes - should work now, sorry about that!

**Comment by cflurin** [comment]
Did you run the latest version? Pairing is broken EVE > "Adding Failed"

**Comment by cflurin** [comment]
... you can find an example (FhemWindowCovering.js) [here](https://github.com/cflurin/homebridge-shims/blob/master/FhemWindowCovering.js)

**Comment by nfarina** [comment]
I'll give it a shot a bit later - I spot-checked the HAP but didn't test pairing; I'm on a network where mdns is disabled.

**Comment by cflurin** [comment]
@nfarina: If it could be useful for testing, I could upload a FakeWindowCovering.js. Let me know.

**Comment by KhaosT** [comment]
@nfarina Please let me know when this is read to be merged, thx :)

**Comment by nfarina** [comment]
@cflurin Could you try again? It turns out HomeKit will reject the accessory if you send a characteristic current value which is outside the bounds of your min/max specs. That fixed it for me.

**Comment by cflurin** [comment]
@nfarina
I was investigating too and I additionally changed AccessoryLoader.js:
```javascript
-    step: json.designedMinStep,
+    minStep: json.designedMinStep,
````
and with your new Characteristic.js now pairing is working :smile:
I'll test the FhemWindowCovering and report ...

**Comment by cflurin** [comment]
... more changes in Import.js
```javascript
  // apply any basic constraints if present
  if (characteristic.Constraints && typeof characteristic.Constraints.maxValue !== 'undefined')
    output.write(",\n    maxValue: " + characteristic.Constraints.maxValue);

  if (characteristic.Constraints && typeof characteristic.Constraints.minValue !== 'undefined')
    output.write(",\n    minValue: " + characteristic.Constraints.minValue);

  if (characteristic.Constraints && typeof characteristic.Constraints.minStep !== 'undefined')
    output.write(",\n    minStep: " + characteristic.Constraints.minStep);
````

**Comment by nfarina** [comment]
Good catch on AccessoryLoader, just pushed that fix! I don't think the change in `import.js` is needed though - those variables like `StepValue` are from HomeKit Accessory Simulator's plist and I don't think they've changed?

**Comment by cflurin** [comment]
Right, the imports.js changes aren't necessary.
I notice that in HomeKitType.js you used following sequence:
```javascript
  this.setProps({
    format: 
    unit: 
    maxValue: 
    minValue: 
    minStep: 
    perms: 
  });
```
In Characteristic.js and AccessoryLoader.js this sequence is broken (minValue first). I didn't change it and it's up to you to modifi it. It my be easier to read but this is really only aesthetics.

**Comment by cflurin** [comment]
... I updated FhemWindowConvering.js which shows how to change the default values of the Characteristic.TargetHorizontalTiltAngle. https://github.com/nfarina/homebridge/issues/181.
It's work for me, PR :+1:

**Comment by snowdd1** [comment]
Looks cool, but I assume it's breaking old references to things like `myService.getCharacteristic(Characteristic.TargetTemperature).minimumValue=0`, so would you mind to put some sentences on how to modify existing shims in the Wiki?

**Comment by cflurin** [comment]
Hi @snowdd1 are you sure that code worked?
I tried firs this way for an optional Characteristic:
```javascript
var FhemWindowCoveringService = new Service.WindowCovering();
this.Characteristic.TargetHorizontalTiltAngle = FhemWindowCoveringService
   .addCharacteristic(Characteristic.TargetHorizontalTiltAngle)
this.Characteristic.TargetHorizontalTiltAngle.minimumValue = 0;
```
But this didn't change the minimValue in HomeKit (EVE).

**Comment by snowdd1** [comment]
It started working with the back end changes nfarina pushed to the hap-nodejs

**Comment by cflurin** [comment]
Strange! the only difference I can see is addCharacteristic instead of getCharacteristic.

**Comment by snowdd1** [comment]
With the code above I get in <bridge>/accessories
````json
			{
				"iid": 12,
				"type": "00000035-0000-1000-8000-0026BB765291",
				"perms": ["pr",
				"pw",
				"ev"],
				"format": "float",
				"value": 10,
				"description": "Target Temperature",
				"unit": "celsius",
				"maximumValue": 40,
				"minimumValue": 0,
				"stepValue": 0.1
			},
```` 
~~which is pretty much what I expected.~~
which shows me my HAP-nodeJS still uses the old property names. Just some minutes I have to update the thing again! I probably have the wrong package.json in my homebridge!

**Comment by snowdd1** [comment]
Ok, here we are:
````json
			{
				"iid": 12,
				"type": "00000035-0000-1000-8000-0026BB765291",
				"perms": ["pr",
				"pw",
				"ev"],
				"format": "float",
				"value": 10,
				"description": "Target Temperature",
				"unit": "celsius",
				"maxValue": 40,
				"minValue": 0,
				"minStep": 0.1
			},
````
Pairs nicely, and also allows temp<10°C in EVE.

**Comment by cflurin** [comment]
```
... and also allows temp<10°C in EVE.
```
does it mean, this wasn't possible with the previous version?

**Comment by snowdd1** [comment]
Right that's why pairing failed so often.

**Comment by cflurin** [comment]
:ok: The effort was worth it. @nfarina thank your for the extension.

**Comment by nfarina** [comment]
Awesome! I think this is ready to merge then.

**Pull request merged**
