### PR TITLE
Support Service display names

### PR DESCRIPTION
**Pull request by nfarina**
- Convert sample Light accessory to new API

### CODE REVIEW

**Comment by KhaosT** [comment]
Looks Nice. One small problem, HomeKit suggests developer to use "name" characteristic to decide if the service should be displayed to user... We shouldn't include "name" characteristic in all services.

**Comment by nfarina** [comment]
Ok let me think on this a bit...

**Comment by nfarina** [comment]
(force pushed) is that more as it should be?

**Comment by nfarina** [comment]
Added some examples of service names in Light/Lock.

**Pull request merged**
