### PR TITLE
Adding configuration for GitHub actions CI

### PR DESCRIPTION
**Pull request by Supereg**
This PR is a proposal to add a CI runner to the project.
There is no real benefit, if we have some unit tests but never run them and regressions potential get published unnoticed.

Additionally I fixed an already broken Tests in this PR.

I don't really care what CI runner we are going to use, I just picked Travis, since the integration with GitHub seems pretty good and it worked for me in the past.
Additionally you could hook up travis to [deploy npm releases](https://docs.travis-ci.com/user/deployment/npm/) (a new version is published for every tagged commit). For me this feature wasn't always reliable, but in every case you would need to finish the setup @KhaosT (setup travis for your account and maybe add deployment tokens).

### CODE REVIEW

**Comment by KhaosT** [comment]
Just curious, have you thought about using GitHub Actions? Seems pretty cool and easier to integrate?

**Comment by Supereg** [comment]
Not really. If the same can be achieved would probably be better to have everything in one place.
Checking the Actions Tab, I would assume only you could configure those?

**Comment by Supereg** [comment]
Just checked, there are some predefined workflows for NPM.
This will create a new yml at `.github/workflows/nodejs.yml` with the following default content
```
name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm ci
        npm run build --if-present
        npm test
      env:
        CI: true
```

Only thing what can be changed should be on to include `pull_request` and remove node-version 8.x and add maybe 13.x

I could change this PR to include this file or you just create the workflow over the actions tab. If we want to use GitHub actions at all.

**Comment by KhaosT** [comment]
Do you have a strong preference going with Travis CI? If not, I can get GitHub Actions configured today ^^

**Comment by Supereg** [comment]
Currently playing around a bit with GitHub actions. And I got now a strong preference to go with GitHub Actions 😂 it's a bit more verbose regarding the configuration but it seems also quite power flow and pretty well integrated.

**Comment by Supereg** [comment]
Added a example config were we also test on any supported platform. Maybe a bit too much 😅 but would be cool if you set up a workflow :)

Additionally I think there is also a 'Node.js Package' workflow for CD which runs on every new release

**Comment by Supereg** [comment]
Okay looking at my test GitHub action it seems like our tests won't run on windows (wasn't windows a supported platform? 😅)

**Comment by Supereg** [comment]
It seems like jest doesn't run at all on windows instances? https://github.com/facebook/jest/issues/9413

**Comment by Supereg** [comment]
Okay, got now a good overview over GitHub Actions. Windows as os can currently not be used as jest just crashes with exist code 1.
Fail-fast is currently on. So when any job fails early all others get cancelled automatically.

Lastly, I think GitHub Actions could get pretty costly:
Bildschirmfoto 2020-01-18 um 20 32 24

This was just me testing some stuff. Don't know how much HAP-NodeJS would consume. We could potentially reduce the amount of node versions tested and exclude macOS as it calculates 10x the minutes for macOS runs lol

**Comment by KhaosT** [comment]
@Supereg GitHub Actions is free for public repo ^^

**Comment by KhaosT** [comment]
@Supereg can you see the run? https://github.com/KhaosT/HAP-NodeJS/runs/397037994

**Comment by Supereg** [comment]
> @Supereg GitHub Actions is free for public repo ^^
Oh lol, must have confused something 

> @Supereg can you see the run?
Yes ☺️👏🏽

**Pull request merged**
